### PR TITLE
Escape quotes, single quotes and backslashes

### LINKED ISSUE #13: escape quotes for commas
creating new enhancement for point brought up in https://github.com/vishysank/console-log-atom/issues/12 by @designofhumanity

### PR DESCRIPTION
**Pull request by pdonias**
Fixes #13

@vishysank Should I make this a settings option?

### CODE REVIEW

**Comment by vishysank** [comment]
I am going to write some tests for these to make sure they work, and if so will merge.

**Comment by pdonias** [comment]
Ok, great!
So should I add an option to disable it in the settings, what do you think?

**Comment by vishysank** [comment]
I think if this works, it will be an improvement to functionality in general so I don't think it needs to be a setting. Will be writing some tests today and tomorrow.

**Comment by vishysank** [comment]
@pdonias added some tests, looks like they pass 👍. However, I made a small adjustment, removed the need to escape double quotes since the identifier is always cased in single quotes, so double quotes should not cause a problem. checkout line 71 in lib/console-log.coffee. What are your thoughts on this ? If you are okay with this I shall go ahead and merge.

**Comment by pdonias** [comment]
Looks good to me :)

**Pull request merged**
